#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
env_file="${1:-"$script_dir/.env"}"

if [[ -e "$env_file" && "${OVERWRITE_ENV:-0}" != "1" ]]; then
  echo "Refusing to overwrite existing env file: $env_file" >&2
  echo "Set OVERWRITE_ENV=1 to replace it." >&2
  exit 1
fi

secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -d '\n' | tr '/+' '_-' | cut -c1-48
  else
    head -c 48 /dev/urandom | base64 | tr -d '\n' | tr '/+' '_-' | cut -c1-48
  fi
}

umask 077
cat >"$env_file" <<EOF
# Generated by wallet-stack/generate-env.sh
# Keep this file private. It contains local RPC credentials.

BITCOIN_RPC_USER=cryptoqr_btc
BITCOIN_RPC_PASSWORD=$(secret)

LITECOIN_RPC_USER=cryptoqr_ltc
LITECOIN_RPC_PASSWORD=$(secret)

MONERO_RPC_USER=cryptoqr_xmr
MONERO_RPC_PASSWORD=$(secret)
MONERO_WALLET_RPC_USER=cryptoqr_xmr_wallet
MONERO_WALLET_RPC_PASSWORD=$(secret)

# Default: Cake Wallet's public Monero remote node. Use monerod:18081 if you
# start the optional local-monero profile.
MONERO_DAEMON_ADDRESS=xmr-node.cakewallet.com:18081

# Provider RPCs keep the stack light. Replace with Alchemy/Infura/QuickNode/Helius/etc.
ETH_RPC_URL=https://ethereum-mainnet.example.invalid
SOL_RPC_URL=https://api.mainnet-beta.solana.com

# Optional: set this after first bootstrap if you want tools/new_address.py
# to derive fresh BTC/LTC/ETH/SOL receive addresses without passing --mnemonic.
BIP39_MNEMONIC=

# Public stablecoin contracts/mints used by the address-generation script.
ETH_USDC_CONTRACT=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
ETH_USDT_CONTRACT=0xdAC17F958D2ee523a2206206994597C13D831ec7
SOL_USDC_MINT=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
SOL_USDT_MINT=Es9vMFrzaCERmJfrF4H2FYD4oQMB3nY7yV5LSD9kL7s
EOF

chmod 600 "$env_file"
echo "Wrote $env_file with mode 600."
